def heart:
    print("   ***  ***")
    print(" *****  *****")
    print("*************")
    print(" *********** ")
    print("  *********  ")
    print("   *******   ")
    print("    *****    ")
    print("     ***     ")
    print("      *      ")
